title: Test Documentation
baseurl: "/NewTest"
url: "http://intuitive-james.github.io/NewTest/"
fixedNav: 'false'
theme: grey

markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
