title: Test Documentation
email: 
description: 
baseurl: "/NewTest"
url: "http://intuitive-james.github.io/NewTest/"
fixedNav: 'false'
theme: grey

# Build settings
permalink: :categories/:title.html
markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
