title: Test Documentation
email: 
description: 
baseurl: "/NewTest"
url: "http://intuitive-james.github.io/NewTest/"
fixedNav: 'false'
theme: grey
twitterUsername: intuitivesystem
githubUsername: intuitive-james

# Build settings
permalink: :categories/:title.html
markdown: kramdown
include: [_pages,categories]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed

  defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

#collections
collections:
    - Transfers
    - Flights
    - Contracting